import telebot
from extensions import APIException, Convertor
from config import *
import traceback


bot = telebot.TeleBot(TOKEN)


@bot.message_handler(commands=["start",])
def rules (message: telebot.types.Message):
    text = f"Приветствую, {message.chat.username} что бы начать введите команду /help"
    bot.reply_to(message,text)


@bot.message_handler(commands=["help"])
def rules (message: telebot.types.Message):
    text = "Для перевода валюты ведите <имя валюты, цену которой хотите узнать> <имя валюты, в которой надо узнать цену первой валюты> <количество первой валюты> " \
        "\nДля просмотра доступных к обмену валют /values"
    bot.reply_to(message,text)


@bot.message_handler(commands=["values"])
def values (message: telebot.types.Message):
    text = "Доступные валюты:"
    for key in exchanges.keys():
        text = '\n'.join((text, key ))
    bot.reply_to(message, text)


@bot.message_handler(content_types=['text'])
def converter(message: telebot.types.Message):
    values = message.text.split(' ')
    try:
        if len(values) != 3:
            raise APIException('Неверное количество параметров!')

        answer = Convertor.get_price(*values)
    except APIException as e:
        bot.reply_to(message, f"Ошибка в команде:\n{e}")
    except Exception as e:
        traceback.print_tb(e.__traceback__)
        bot.reply_to(message, f"Неизвестная ошибка:\n{e}")
    else:
        bot.reply_to(message, answer)


bot.polling()
